### ISSUE TITLE
v1.1

### ISSUE THREAD

**Issue by caiquevitoriano** [ads-ifpb-gcm/projeto-vem-pra-ads#1]
modificações da v1.1
 Informações sobre o Campus e Informações sobre Cajazeiras

**Comment by beniciojackson** [comment]
massa

**Comment by beniciojackson** [comment]
@rogerioalcantaracz  tira essa parte  html ADSHTML5 UP

**Comment by rogerioalcantaracz** [comment]
Blz,agora!

**Comment by rogerioalcantaracz** [comment]
@caiquevitoriano fazer os tópicos localização da cidade e a breve história

**Comment by beniciojackson** [comment]
@rogerioalcantaracz  EI FAÇA AI Informações sobre Cajazeiras
Opções de lazer
Fotos da cidade

**Comment by beniciojackson** [comment]
@rogerioalcantaracz  ei rogerio ajeita ai a imagem da bolinha de informaçoes sobre cajazeiras deixa ela grande 500x500x
