### ISSUE TITLE
lista com alunos egressos 

### ISSUE THREAD

**Issue by caiquevitoriano** [ads-ifpb-gcm/projeto-vem-pra-ads#2]
@diogomoreira

**Comment by diogomoreira** [comment]
Quanto aos alunos que estão trabalhando, caso você não conheça nenhum, pode colocar só a lista das empresas que já tivemos/temos ex-alunos trabalhando.
EBIX, CAST Tecnologia, BRQ, Trana, Indra Company, Phoebus Tecnologia, Accenture, Stefanini, Dynavideo, Digivox, Ruppells Griffon (Austrália), Instituto Federal da Paraíba (IFPB), Instituto Federal de Pernambuco (IFPE), UEPB, UFC

Quanto ao mestrado, nossos alunos já estiveram em:
UFPB, UFCG e C.E.S.AR.
